### ISSUE TITLE
It should avoid exceeding the number of clicks required by the current difficulty before hiding the cards

### ISSUE THREAD

**Issue by Jonatandb** [Jonatandb/memory-game#2]
It should avoid exceeding the number of clicks required by the current difficulty before hiding the cards.

Difficulty------Maximum allowed consecutive clicks before hiding the cards:
Fácil---------->2
Medio-------->3
Difícil--------->4

**Comment by ChandanaReddy07** [comment]
Can I look into this issue?

**Comment by Jonatandb** [comment]
> Can I look into this issue?

Yes!, you can, thanks 😉👌🏻

**Comment by ChandanaReddy07** [comment]
Hey buddy! I have kept a pr check if it meets the need.

**Comment by Jonatandb** [comment]
Thank you, it works perfectly 👌🏻👏🏻

**Comment by Jonatandb** [comment]
> Hey buddy! I have kept a pr check if it meets the need.


Thank you, it works perfectly 👌🏻👏🏻

**Comment by Jonatandb** [comment]
I discovered that it fails when you increase the difficulty because you need to match 3 or 4 cards, which requires more than 2 consecutive clicks in those cases.

**Comment by Jonatandb** [comment]
Solved by https://github.com/Jonatandb/memory-game/commit/1a19d8aaae4d974e609d3d126832435506f181b0
